### ISSUE TITLE
Disappearing template loop items

### ISSUE THREAD

**Issue by zepfietje** [alpinejs/alpine-turbolinks-adapter#12]
I'm using this adapter on a Livewire + Alpine project which uses Turbolinks.
Previously, template loop items (`<template x-for="">`) were being duplicated when navigating back and forth.
This adapter resolves that issue. However, it causes other (sibling) template loops to disappear when navigating.

Let me know if there's any specific information we need to debug this issue.

**Comment by SimoTod** [comment]
Thanks for the bug report.Just to clarify. Are we saying that something like 
```html
<div data="{foo: ['one', 'two'], bar: ['red', 'blue']}">
    <template x-for="item1 in foo">
        <p x-text="item1"></p>
    <template>
    <template x-for="item2 in bar">
        <p x-text="item2"></p>
    <template>
</div>
```
will result in the second loop being removed when navigating back to the page?
```
<div data="{foo: ['one', 'two'], bar: ['red', 'blue']}">
    <template x-for="item1 in foo">
        <p x-text="item1"></p>
    <template>
</div>
```

**Comment by zepfietje** [comment]
@SimoTod, thanks for your clear snippets. That's exactly what seems to happen when using the adapter.

I haven't put together a minimal reproducible example though.

**Comment by SimoTod** [comment]
No worries I'll try to have a look tonight/tomorrow and let you know

**Comment by SimoTod** [comment]
@zepfietje
I was able to replicate and find the bug (https://github.com/alpinejs/alpine-turbolinks-adapter/commit/705d496108ca8b8b8760bc05e73df5ff2b6e59e3 😄 ).

Before I tag a new release, could you try https://cdn.jsdelivr.net/gh/alpinejs/alpine-turbolinks-adapter@bug/sibling-x-for-disappearing/dist/alpine-turbolinks-adapter.min.js and confirm it resolves your bug please? Thanks.

**Comment by zepfietje** [comment]
@SimoTod awesome! I can confirm it resolves the bug in my project.

**Comment by SimoTod** [comment]
Thanks for confirming. I tagged a new version. It's a patch release so if you use the generic CDN link (0.1.x) you won't need to update the link. Since served by a CDN (I don't have control over it), it could take up to 24h to update.

**Comment by zepfietje** [comment]
@SimoTod, thanks again for the quick fix!
