### ISSUE TITLE
Figure out if the plugin is testable somehow

### ISSUE THREAD

**Issue by SimoTod** [alpinejs/alpine-turbolinks-adapter#3]
As it says on the tin. It would be good to be able to write tests although it seems challenging because the way turbolinks works.

**Comment by HugoDF** [comment]
Would it be worth using something like Cypress or other E2E testing solution?

Dunno how much sense unit testing the adapter makes, but having a couple of use cases running against a some HTML files would be good value/effort

**Comment by SimoTod** [comment]
Yeah, I think it would be good to test the use case that the library is supposed to solve.
I had a first go with puppeteer but it just doesn't work and I don't understand why, lol. (https://github.com/alpinejs/alpine-turbolinks-adapter/pull/new/tests).

**Comment by ryangjchandler** [comment]
I've got a feeling Cypress is going to be better for this than a Puppeteer setup. Let me know if you need any help.

**Comment by SimoTod** [comment]
yeah, I just picked a random one since I don't have any experience with that. I'll try cypress. 👍

**Comment by ryangjchandler** [comment]
Let us know if you need any help :)

**Comment by SimoTod** [comment]
@ryangjchandler is there a way to run cypress without relying on the fact that I have a browser installed on my machine (like puppeteer does)?

**Comment by ryangjchandler** [comment]
@SimoTod most browser test suites need an actual browser instance to run. Cypress has a good GitHub Action though which bootstraps the environment etc.

**Comment by SimoTod** [comment]
Cool, it seems that cypress from terminal runs using electron by default. I don't think I need the dashboard so I'll just use a standard test action for now (https://github.com/alpinejs/alpine-turbolinks-adapter/actions/runs/175728156). Thanks for your advice, cypress seems way easier than puppeteer. 👍

**Comment by SimoTod** [comment]
Cypress seems to do the job. Thanks everybody.
