### ISSUE TITLE
How can I keep the cdn link updated

### ISSUE THREAD

**Issue by tanthammar** [alpinejs/alpine-turbolinks-adapter#6]
Hi.
Thank you for this fix.
How can I keep the cdn link updated.
Currently I am using this in my app
```html
    <script src="https://cdn.jsdelivr.net/gh/SimoTod/alpine-turbolinks-adapter@eac088b4067e1a8d8ea21b5182458b8afb9435ac/dist/alpine-turbolinks-adapter.min.js" defer></script>

```
But I see you've made commits since I got that link from you in our discord chat.

//Tina

**Comment by HugoDF** [comment]
I think you can just omit the `@` and it will fetch the latest version

```
https://cdn.jsdelivr.net/gh/SimoTod/alpine-turbolinks-adapte/dist/alpine-turbolinks-adapter.min.js
```

Note that you probably don't want to do the above in production (and that I haven't tested it 😁)

**Comment by SimoTod** [comment]
the additional commit is a dev fix, it won't affect the cdn output so the previous link is still okay.
If you want, you can use
<script src="https://cdn.jsdelivr.net/gh/SimoTod/alpine-turbolinks-adapter@master/dist/alpine-turbolinks-adapter.min.js" defer></script> in dev to get the latest version (although the cdn has a 24h delay).

I should be able to move the library under the alpine namespace and tag a proper release over the weekend.
Just to know, are you using it on a website in prod? I need to know so I won't break your website when I do it.

**Comment by tanthammar** [comment]
Hi, no, it is still in dev. And I am fine with the link as it is, no stress. :)

**Comment by SimoTod** [comment]
Cool, I'll let you know once I tag a stable release ready for prod.

**Comment by SimoTod** [comment]
@tanthammar 
I've transferred the repo to the alpinejs namespace so the link for the alpha version has changed to
`https://cdn.jsdelivr.net/gh/alpinejs/alpine-turbolinks-adapter@eac088b4067e1a8d8ea21b5182458b8afb9435ac/dist/alpine-turbolinks-adapter.min.js`
I believe the old link will still be available for about 24h due to the CDN but you need to update it on Monday when you are back to work.
